# -*- coding: utf-8 -*-
"""covariance_matrix_cmap coolwarm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O5x9GAXI8s6PW8Bi2b2u463ryA859YCp
"""

import os
import torch
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')

from transformers import AutoTokenizer, AutoModelForCausalLM
from huggingface_hub import login
from torch.nn.functional import cosine_similarity
from sklearn.decomposition import PCA

MODEL_NAME = "meta-llama/Llama-3.2-1B-Instruct"
FIG_DIR = "figures"
INPUT_FILE = "text.txt"

os.makedirs(FIG_DIR, exist_ok=True)

device = "cuda" if torch.cuda.is_available() else "cpu"

# ============================================================
# Load model & tokenizer
# ============================================================
login()
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float32,
    device_map="auto"
)

model.eval()

attn_outputs = {}

def make_attn_hook(layer_id):
    def hook(module, inp, out):
        # out can be a tensor or a tuple
        if isinstance(out, tuple):
            attn_outputs[layer_id] = out[0].detach().cpu()
        else:
            attn_outputs[layer_id] = out.detach().cpu()
    return hook

for layer_id, layer in enumerate(model.model.layers):
    layer.self_attn.register_forward_hook(make_attn_hook(layer_id))

INPUT_FILE = "text.txt"

with open(INPUT_FILE, "r", encoding="utf-8") as f:
    text = f.read().strip()

max_len = 256
inputs = tokenizer(text, return_tensors="pt",truncation=True,max_length=max_len).to(device)

with torch.no_grad():
    outputs = model(**inputs)

first_layer = list(attn_outputs.keys())[0]
seq_len = attn_outputs[first_layer].shape[1]

svd_vals = {}      # valeurs singulières
svd_vecs = {}      # vecteurs singuliers droits
k_svd = {}         # dimension retenue
cosine_raw = {}    # cosine similarity brute
cosine_svd = {}    # cosine similarity après projection

p = 0.9
for layer_id, X in attn_outputs.items():

    # -------------------------
    # Données
    # -------------------------
    X = X.squeeze(0).numpy()  # (T, d)

    # -------------------------
    # Cosine similarity brute
    # -------------------------
    X_norm = X / np.linalg.norm(X, axis=1, keepdims=True)
    cosine_raw[layer_id] = X_norm @ X_norm.T

    # -------------------------
    # SVD non centrée
    # -------------------------
    U, S, Vt = np.linalg.svd(X, full_matrices=False)
    V = Vt.T

    svd_vals[layer_id] = S
    svd_vecs[layer_id] = V

    # -------------------------
    # Sélection automatique de k (énergie p%)
    # -------------------------
    energy = S**2
    cum_energy = np.cumsum(energy) / np.sum(energy)
    k = np.searchsorted(cum_energy, p) + 1
    k_svd[layer_id] = k

    # -------------------------
    # Projection SVD
    # -------------------------
    X_proj = X @ V[:, :k]

    # -------------------------
    # Cosine similarity projetée
    # -------------------------
    X_proj_norm = X_proj / np.linalg.norm(X_proj, axis=1, keepdims=True)
    cosine_svd[layer_id] = X_proj_norm @ X_proj_norm.T

#Figures — Valeurs singulières
SVD_DIR = os.path.join(FIG_DIR, "svd_vals")
os.makedirs(SVD_DIR, exist_ok=True)

for layer_id, S in svd_vals.items():
    plt.figure(figsize=(6,4))
    plt.plot(S, marker='o', linestyle='-', markersize=3)
    plt.yscale("log")
    plt.xlabel("Singular value index")
    plt.ylabel("Singular value (log scale)")
    plt.title(f"Layer {layer_id} – Singular values")
    plt.grid(True, which="both", ls="--", alpha=0.5)

    fname = os.path.join(SVD_DIR, f"layer_{layer_id}_svd_vals.png")
    plt.savefig(fname, bbox_inches="tight")
    plt.close()

#Figures — Cosine similarity brute
COS_RAW_DIR = os.path.join(FIG_DIR, "cosine_raw")
os.makedirs(COS_RAW_DIR, exist_ok=True)

for layer_id, cos_sim in cosine_raw.items():
    plt.figure(figsize=(6,5))
    plt.imshow(cos_sim, cmap="coolwarm", vmin=-1, vmax=1)
    plt.colorbar(label="Cosine similarity")
    plt.title(f"Layer {layer_id} – Cosine similarity (raw)")
    plt.xlabel("Token index")
    plt.ylabel("Token index")
    plt.tight_layout()

    fname = os.path.join(COS_RAW_DIR, f"layer_{layer_id}_cosine_raw.png")
    plt.savefig(fname, bbox_inches="tight")
    plt.close()

#Figures — Cosine similarity après projection SVD
COS_SVD_DIR = os.path.join(FIG_DIR, "cosine_svd_proj")
os.makedirs(COS_SVD_DIR, exist_ok=True)

for layer_id, cos_sim in cosine_svd.items():
    plt.figure(figsize=(6,5))
    plt.imshow(cos_sim, cmap="coolwarm", vmin=-1, vmax=1)
    plt.colorbar(label="Cosine similarity")
    plt.title(f"Layer {layer_id} – Cosine similarity (SVD p={p})")
    plt.xlabel("Token index")
    plt.ylabel("Token index")
    plt.tight_layout()

    fname = os.path.join(COS_SVD_DIR, f"layer_{layer_id}_cosine_svd_proj.png")
    plt.savefig(fname, bbox_inches="tight")
    plt.close()